version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - K8S_MODEL=${K8S_MODEL:-gemini-2.0-flash}
      - K8S_TEMPERATURE=${K8S_TEMPERATURE:-0.1}
      - K8S_MAX_TOKENS=${K8S_MAX_TOKENS:-2048}
      - K8S_NAMESPACE=${K8S_NAMESPACE:-default}
      - K8S_MAX_REPLICAS=${K8S_MAX_REPLICAS:-10}
    volumes:
      - ~/.kube:/home/app/.kube:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: k8s-ai-agent